---
title: "Data analyses for Global Typhoid Genomics Consortium Paper - Working Group 1 (Descriptive Stats - trees)"
author: "Kat Holt"
date: "03/12/2022"
output:
  html_document:
    toc: true
#    toc_float: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = getwd())

# Data wrangling
library(tidyverse)
library(dplyr)

# Plotting (general)
library(ggplot2)
library(patchwork)

# trees
library(treeio)
library(ggtree)
library(ggnewscale)

```

# Load metadata
``` {r load_data}
tgc_all <- read_csv("../TGC_data_031222.csv")
```

# 4.3.1.1.P1 tree

## load tree
``` {r}
# tipnames match on 'DisplayName' column
t <- read.tree("pathogenwatch-styphi-5bremw9hym3y-rwp1-pk1-context-collection-tree.nwk")

t_noOutgroup <- drop.tip(t, "4714STDY6831711") # drop 3.0.1 outlier as it obscures detail
t_noOutgroup <- drop.tip(t_noOutgroup, "4714STDY6837119") # drop long branch strain 4714STDY6837119
```

## prepare data
``` {r}
tree_data <- tgc_all %>% 
  select(DisplayName, Final_genotype, Year, `blaCTX-M-15_23`, gyrA_S83F, qnrS, MDR, XDR) %>% 
  filter(DisplayName %in% t_noOutgroup$tip.label) %>%
  rename(`blaCTX-M-15`=`blaCTX-M-15_23`) %>%
  rename(label=DisplayName) %>%
  mutate(`blaCTX-M-15` = if_else(`blaCTX-M-15`==1, "present", "absent")) %>%
  mutate(qnrS = if_else(qnrS==1, "present", "absent")) %>%
  mutate(gyrA_S83F = if_else(gyrA_S83F==1, "present", "absent")) %>%
  mutate(MDR = if_else(MDR, "present", "absent")) %>%
  mutate(XDR = if_else(XDR, "present", "absent"))

tree_data_forObject <- tree_data %>% select(label, Final_genotype) %>% mutate(rw=if_else(label=="Rwp1-PK1", "Rwp1-PK1", ""))
tree_data_forHeatmap <- tree_data %>% select(-Final_genotype)

# set genotype colours
geno_info <- read_csv("https://raw.githubusercontent.com/katholt/genotyphi/main/Genotype_specification.csv") %>% filter(Genotype %in% tree_data$Final_genotype)
geno_colours <- geno_info$`Colour code`
names(geno_colours) <- geno_info$Genotype
geno_colours <- geno_colours[order(names(geno_colours))] # sort for legend

# join tree and genotype data
treedat <- full_join(as_tibble(t_noOutgroup), tree_data_forObject, by = 'label')
mrca_p1 <- MRCA(treedat, na.omit(treedat$node[treedat$Final_genotype=="4.3.1.1.P1"]))
rw <- treedat$node[treedat$label=="Rwp1-PK1"][1]

```

## build tree plot
``` {r}
tree_plot <- ggtree(as.treedata(treedat)) + 
  geom_highlight(node=mrca_p1$node, fill="orange", alpha=.25, extend=5) + 
  geom_tippoint(aes(color = Final_genotype, shape=rw)) +
  geom_text(aes(label=rw), hjust=-0.1, size=2.5, vjust=0.1) +
  scale_colour_manual(values = geno_colours) +
  labs(color="Genotype") + vexpand(.08, 1) + guides(shape="none")

# heatmaps of AMR determinants
tree_data_matrix <- data.frame(tree_data_forHeatmap)
row.names(tree_data_matrix) <- tree_data_matrix[,1]
tree_data_matrix <- tree_data_matrix[,-1]

year<-as.matrix(tree_data_matrix[,1])
rownames(year) <- rownames(tree_data_matrix)
colnames(year)="Year"

# plot tree with heatmaps
XDR_tree_part1 <- gheatmap(tree_plot, year, width=0.055, colnames_angle=60, colnames_position="top", hjust=0, font.size=2.5, custom_column_labels=c("Year"), colnames_offset_x=-0.2, offset=1) + 
  scale_fill_manual(values=c(`2015`="yellow", `2016`="orange", `2017`="red", `2019`="brown") ) +
  labs(fill="Year") + new_scale_fill()

XDR_tree_part2 <- gheatmap(XDR_tree_part1, tree_data_matrix[,-1], width=0.25, colnames_angle=60, colnames_position="top", hjust=0, font.size=2.5, custom_column_labels=c("CTX-M-15", "GyrA-S83F", "qnrS", "MDR", "XDR"), colnames_offset_x=-0.2, offset=2) + 
  scale_fill_manual(values=c(present="navy", absent="lightgrey") ) +
  labs(fill="AMR") 

XDR_tree_part2

```

## Fig 4: Pathogenwatch tree of Pakistan isolates showing position of Rwp1-PK1
``` {r, eval=T}

pdf(file="Fig4_Rwp1-PK1_Pakistan_tree.pdf",width=6, height=8)
XDR_tree_part2
dev.off()

png(file="Fig4_Rwp1-PK1_Pakistan_tree.png",width=6, height=8, units="in", res=400)
XDR_tree_part2
dev.off()

```

# 2.3.2 tree

## load tree and link data
``` {r}
# tree of n=164 2.3.2 plus genomes from Ingle et al, 2021 to use as outgroups to root the 2.3.2 subtree; tree generated using Pathogenwatch
t232_outgroups <- read.tree("pathogenwatch-styphi-ghqgw866b3dl-typhi-232-plus-outgroups-collection-tree.nwk")

tips232 <- read_csv("pw232_to_ID.csv")

```

## join tree and data
``` {r}

# get metadata for plotting, col1 = PW_NAME matches the tree
tgc_232 <- left_join(tips232, tgc_all) %>% 
  select(PW_NAME, Region, cipNS, Final_genotype) %>%
  mutate(Region = replace(Region, is.na(Region), "Not Provided")) %>%
  rename(label=PW_NAME)

# join full tree and 2.3.2 data
treedat_232_outgroups <- full_join(as_tibble(t232_outgroups), tgc_232, by = c("label"))

# find MRCA node for 2.3.2 genomes
mrca_232 <- MRCA(treedat_232_outgroups, na.omit(treedat_232_outgroups$node[treedat_232_outgroups$Final_genotype=="2.3.2"]))

# extract subtree for 2.3.2
t232 <-tree_subset(t232_outgroups, mrca_232$node, levels_back = 0)

# attach data for plotting
treedat_232 <- full_join(as_tibble(t232), tgc_232, by = c("label"))

```

## build tree plot
``` {r}

# prepare region variable and colours
treedat_232 <- treedat_232 %>% 
  mutate(Region = replace(Region, Region %in% c("Northern Europe", "Southern Europe", "Western Europe"), "Europe")) %>% 
  mutate(Region = replace(Region, Region %in% c("Southern Asia", "South-eastern Asia", "Western Asia"), "Asia")) %>% 
  mutate(Region = replace(Region, Region %in% c("Southern Africa", "Middle Africa"), "Other Africa")) %>%
  mutate(internal_node = replace(node, !is.na(label), NA))

treedat_232$Region <- factor(treedat_232$Region, levels=c("Caribbean", "Central America", "South America", "Northern America", "Western Africa", "Other Africa", "Asia", "Polynesia", "Europe", "Not Provided"))
  
region_cols <- c(Caribbean = "gold1", 
                    `Central America` = "darkorange",
                    `South America` =  "#d31e25", # red
                    `Northern America` = "magenta4",
                    `Western Africa` = "dodgerblue3", 
                    `Other Africa` = "#369e4b", # green 
                    Asia = "hotpink1", 
                    Polynesia = "black", 
                    Europe = "purple",
                    `Not Provided` = "grey")

# nodes defining regional clades
central_america_clade <- 171
west_africa_clade_1 <- 249
west_africa_clade_2 <- 254
west_africa_clade_3 <- 281
caribbean_clade <- 261
south_america_clade <- 270
  
tree_232_plot <- ggtree(as.treedata(treedat_232)) + 
  geom_highlight(node=central_america_clade, fill=region_cols["Central America"], alpha=.25, extend=5) + 
  geom_highlight(node=west_africa_clade_1, fill=region_cols["Western Africa"], alpha=.25, extend=5) + 
  geom_highlight(node=west_africa_clade_2, fill=region_cols["Western Africa"], alpha=.25, extend=5) + 
  geom_highlight(node=west_africa_clade_3, fill=region_cols["Western Africa"], alpha=.25, extend=5) + 
  geom_highlight(node=caribbean_clade, fill=region_cols["Caribbean"], alpha=.25, extend=5) + 
  geom_highlight(node=south_america_clade, fill=region_cols["South America"], alpha=.25, extend=5) + 
  geom_tippoint(aes(color = Region, shape=cipNS)) +
  scale_colour_manual(values = region_cols) +
  labs(color="Region", shape="CipNS") + vexpand(.08, 1)

tree_232_plot
```

## Fig S4: Outgroup-rooted Pathogenwatch tree of 2.3.2 isolates
``` {r, eval=T}

pdf(file="FigS4_232_tree.pdf",width=6, height=6)
tree_232_plot
dev.off()

png(file="FigS4_232_tree.png",width=6, height=6, units="in", res=400)
tree_232_plot
dev.off()

```